"""remove_salt_from_users_and_nullify_passwords

Revision ID: 236a819e3b88
Revises: 970db38526ce
Create Date: 2025-06-18 02:26:37.454529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236a819e3b88'
down_revision: Union[str, None] = '970db38526ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullify existing passwords first
    op.execute('UPDATE users SET hashed_password = NULL')
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=True))
    # Passwords remain NULL as they cannot be meaningfully restored
    # ### end Alembic commands ###
